export { StarIcon } from "./StarIcon";
export { DeleteIcon } from "./DeleteIcon";
export { QuantityBtnMinus } from "./QuantityBtnMinus";
export { QuantityBtnPlus } from "./QuantityBtnPlus";
export { EarthIcon } from "./EarthIcon";
export { VkIcon } from "./VkIcon";
export { TgIcon } from "./TgIcon";
export { WhatsUpIcon } from "./WhatsUpIcon";
export { MainLogo } from "./MainLogo";
